name: atonline_api
description: AtOnline API tools for Flutter, for use with AtOnline.com APIs including CMS, Naka, etc.
version: 0.4.19
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  mime: ^1.0.5
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  app_links: ^6.3.2
  intl: ^0.19.0
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# Command-line tools
executables:
  atonline_describe: describe

# This specifies which packages are needed for the CLI tool
# but not required when just using the library
# https://dart.dev/tools/pub/dependencies#dependency-only-used-in-executables
dependency_overrides:
  args: ^2.4.2

