name: atonline_api
description: AtOnline API tools for Flutter, for use with AtOnline.com APIs including CMS, Naka, etc.
version: 0.4.13
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.0.0
  mime: ^1.0.4
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.11
  uni_links: ^0.5.1
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

