name: atonline_login
description: Client-side login page for applications using AtOnline apis and custom realms
version: 0.4.0
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.1
  url_launcher: ^6.0.12 # flutter team
  image_picker: ^0.8.4+2 # flutter team
  atonline_api: ^0.4.0
  flutter_svg: ">=0.21.0 <0.24.0"
  flutter_web_auth: ^0.3.1 # non official

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
