name: atonline_login
description: Client-side login page for applications using AtOnline apis and custom realms
version: 0.6.5
homepage: https://github.com/AtOnline/atonline-flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.5
  url_launcher: ^6.3.0 # flutter team
  image_picker: ^1.1.2 # flutter team
  atonline_api: ^0.5.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
